czat/urls.py
# -*- coding: utf-8 -*-
# czat/urls.py

from django.conf.urls import url
from . import views  # import widoków aplikacji
from django.contrib.auth.forms import UserCreationForm
from django.views.generic.edit import CreateView
from django.core.urlresolvers import reverse_lazy
from django.contrib.auth import views as auth_views
from django.contrib.auth.decorators import login_required
from django.views.generic import ListView
from czat.models import Wiadomosc, Nieobecnosc
from django.views.generic import DeleteView
from django.contrib.auth.models import User
from django.urls import reverse

app_name = 'czat'  # przestrzeń nazw aplikacji
urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^user', views.UserList.as_view(paginate_by=5),
        name='users'),
    url(r'^edit/(?P<pk>\d+)/', login_required(
        views.EdytujUser.as_view()),
        name='edit'),
    url(r'^usunuser/(?P<pk>\d+)/',login_required(
        DeleteView.as_view(
            model = User,
            template_name='czat/user_usun.html',
            success_url='/users')),
        name='usunuser'),
    url(r'^rejestruj/', CreateView.as_view(
        template_name='czat/rejestruj.html',
        form_class=UserCreationForm,
        success_url='/'), name='rejestruj'),
    url(r'^loguj/', auth_views.login,
        {'template_name': 'czat/loguj.html'},
        name='loguj'),
    url(r'^wyloguj/', auth_views.logout,
        {'next_page': reverse_lazy('czat:index')},
        name='wyloguj'),
    url(r'^wiadomosci/', login_required(
        ListView.as_view(
            model=Wiadomosc,
            context_object_name='wiadomosci',
            paginate_by=10)),
        name='wiadomosci'),
    url(r'^nieobecnosci/', login_required(
        ListView.as_view(
            model=Nieobecnosc,
            context_object_name='nieobecnosci',
            paginate_by=10)),
        name='nieobecnosci'),
    url(r'^dodaj/$', login_required(
        views.DodajWiadomosc.as_view(),
        login_url='/loguj'),
        name='dodaj'),
    url(r'^dodajn/$', login_required(
        views.DodajNieobscnosc.as_view(),
        login_url='/loguj'),
        name='dodajn'),
    url(r'^edytuj/(?P<pk>\d+)/', login_required(
        views.EdytujWiadomosc.as_view(),
        login_url='/loguj'),
        name='edytuj'),
    url(r'^edytujn/(?P<pk>\d+)/', login_required(
        views.EdytujNieobecnosc.as_view(),
        login_url='/loguj'),
        name='edytujn'),
    url(r'^usun/(?P<pk>\d+)/', login_required(
        DeleteView.as_view(
            model=Wiadomosc,
            template_name='czat/wiadomosc_usun.html',
            success_url='/wiadomosci'),
        login_url='/loguj'),
        name='usun'),
    url(r'^usunn/(?P<pk>\d+)/', login_required(
        DeleteView.as_view(
            model=Nieobecnosc,
            template_name='czat/nieobecnosc_usun.html',
            success_url='/nieobecnosci'),
        login_url='/loguj'),
        name='usunn'),
]

czat2/urls.py
from django.conf.urls import url, include
from django.contrib import admin


urlpatterns = [
    url(r'^', include('czat.urls')),
    url(r'^admin/', admin.site.urls),
]

czat/models.py
# -*- coding: utf-8 -*-
# czat/models.py

from django.db import models
from django.contrib.auth.models import User


class Wiadomosc(models.Model):

    """Klasa reprezentująca wiadomość w systemie"""
    tekst = models.CharField('treść wiadomości', max_length=250)
    data_pub = models.DateTimeField('data publikacji')
    autor = models.ForeignKey(User)

    class Meta:  # ustawienia dodatkowe
        verbose_name = u'wiadomość'  # nazwa obiektu w języku polskim
        verbose_name_plural = u'wiadomości'  # nazwa obiektów w l.m.
        ordering = ['data_pub']  # domyślne porządkowanie danych

    def __str__(self):
        return self.tekst  # "autoprezentacja"

class Nieobecnosc(models.Model):
    
    """Klasa reprezentująca nieobecność pracownika w systemie"""
    tekst = models.CharField('powod nieobecnosci',max_length=100)
    data_pub = models.DateTimeField('data zgłoszenia')
    data_start = models.DateField('data pierwszego dnia nieobecnosci')
    data_koniec = models.DateField('data ostatniego dnia nieobecnosci')
    autor = models.ForeignKey(User)

    class Meta:
        verbose_name = u'nieobecność'  # nazwa obiektu w języku polskim
        verbose_name_plural = u'nieobecności'  # nazwa obiektów w l.m.
        ordering = ['data_pub']  # domyślne porządkowanie danych

    def __str__(self):
        return self.tekst  # "autoprezentacja"

czat/forms.py
# -*- coding: utf-8 -*-
# czat/forms.py

from django.forms import ModelForm, TextInput
from czat.models import Wiadomosc, Nieobecnosc
from django.contrib.auth.models import User

class EdytujWiadomoscForm(ModelForm):
    class Meta:
        model = Wiadomosc
        fields = ['tekst', 'data_pub']
        exclude = ['autor']
        widgets = {'tekst': TextInput(attrs={'size': 60})}

class EdytujNieobecnoscForm(ModelForm):
    class Meta:
        model = Nieobecnosc
        fields = ['tekst', 'data_pub','data_start','data_koniec']
        exclude = ['autor']
        widgets = {'tekst': TextInput(attrs={'size': 60})}

class EdytujUserForm(ModelForm):
    class Meta:
        model = User
        fields = ['username','email','first_name','last_name']
        exclude = ['password','date_joined','is_active','is_staff','is_superuser','last_login']

czat/views.py
# -*- coding: utf-8 -*-
# czat/views.py

from django.shortcuts import render
# from django.http import HttpResponse
from django.views.generic.edit import CreateView
from czat.models import Wiadomosc, Nieobecnosc
from django.utils import timezone
from django.contrib import messages
from django.views.generic.edit import UpdateView
from django.views.generic import View, ListView, DetailView, DeleteView
from django.contrib.auth.models import User
from django.urls import reverse

def index(request):
    """Strona główna aplikacji."""
    # return HttpResponse("Witaj w aplikacji Czat!")
    return render(request, 'czat/index.html')

class UserList(ListView):
    model = User

class UserDetail(DetailView):
    model = User


class EdytujUser(UpdateView):
    model = User
    from czat.forms import EdytujUserForm
    form_class = EdytujUserForm
    context_object_name = 'users'
    template_name = 'czat/user_form.html'
    success_url = '/users'

#    def get_context_data(self, **kwargs):
#        context = super(EdytujUser, self).get_context_data(**kwargs)
#        context['wiadomosci'] = Wiadomosc.objects.filter(
#            autor=self.request.user)
#        return context

    def get_object(self, queryset=None):
        user = User.objects.get(id=self.kwargs['pk'])
        return user

class DodajWiadomosc(CreateView):
    model = Wiadomosc
    fields = ['tekst', 'data_pub']
    context_object_name = 'wiadomosci'
    success_url = '/wiadomosci'

    def get_initial(self):
        initial = super(DodajWiadomosc, self).get_initial()
        initial['data_pub'] = timezone.now()
        return initial

    def get_context_data(self, **kwargs):
        context = super(DodajWiadomosc, self).get_context_data(**kwargs)
        context['wiadomosci'] = Wiadomosc.objects.all()
        return context

    def form_valid(self, form):
        wiadomosc = form.save(commit=False)
        wiadomosc.autor = self.request.user
        wiadomosc.save()
        messages.success(self.request, "Dodano wiadomość!")
        return super(DodajWiadomosc, self).form_valid(form)

class EdytujWiadomosc(UpdateView):
    model = Wiadomosc
    from czat.forms import EdytujWiadomoscForm
    form_class = EdytujWiadomoscForm
    context_object_name = 'wiadomosci'
    template_name = 'czat/wiadomosc_form.html'
    success_url = '/wiadomosci'

    def get_context_data(self, **kwargs):
        context = super(EdytujWiadomosc, self).get_context_data(**kwargs)
        context['wiadomosci'] = Wiadomosc.objects.filter(
            autor=self.request.user)
        return context

    def get_object(self, queryset=None):
        wiadomosc = Wiadomosc.objects.get(id=self.kwargs['pk'])
        return wiadomosc

class DodajNieobscnosc(CreateView):
    model = Nieobecnosc
    fields = ['tekst','data_pub','data_start','data_koniec']
    context_object_name = 'nieobecnosci'
    success_url = '/nieobecnosci'

    def get_initial(self):
        initial = super(DodajNieobscnosc, self).get_initial()
        initial['data_pub'] = timezone.now()
        return initial

    def get_context_data(self, **kwargs):
        context = super(DodajNieobscnosc, self).get_context_data(**kwargs)
        context['nieobecnosci'] = Nieobecnosc.objects.all()
        return context

    def form_valid(self, form):
        nieobecnosc = form.save(commit=False)
        nieobecnosc.autor = self.request.user
        nieobecnosc.save()
        messages.success(self.request, "Zgłoszono nieobecnosc!")
        return super(DodajNieobscnosc, self).form_valid(form)

class EdytujNieobecnosc(UpdateView):
    model = Nieobecnosc
    from czat.forms import EdytujNieobecnoscForm
    form_class = EdytujNieobecnoscForm
    context_object_name = 'nieobecnosci'
    template_name = 'czat/nieobecnosc_form.html'
    success_url = '/nieobecnosci'

    def get_context_data(self, **kwargs):
        context = super(EdytujNieobecnosc, self).get_context_data(**kwargs)
        context['nieobecnosci'] = Nieobecnosc.objects.filter(
            autor=self.request.user)
        return context

    def get_object(self, queryset=None):
        nieobecnosc = Nieobecnosc.objects.get(id=self.kwargs['pk'])
        return nieobecnosc

czat/templates/czat/baza.html
<!-- templates/czat/baza.html -->
{% load staticfiles %}
<!DOCTYPE html>
<html lang="pl">
  <meta charset="utf-8" />
  <head>
    <title>{% block tytul %} Zarządzanie HR {% endblock tytul %}</title>
    <link rel="stylesheet" type="text/css" href="{% static 'css/czat.css' %}" />
  </head>
  <body>
    <h1>{% block naglowek %} Witaj w aplikacji do zarządzania zasobami ludzkimi {% endblock %}</h1>

    {% block komunikaty %}
      {% if messages %}
        <ul>
          {% for komunikat in messages %}
            <li>{{ komunikat|capfirst }}</li>
          {% endfor %}
        </ul>
      {% endif %}
    {% endblock %}

    {% block tresc %} {% endblock %}

    {% if user.is_authenticated %}
      {% block linki1 %} {% endblock %}
      <p><a href="{% url 'czat:wyloguj' %}">Wyloguj się</a></p>
    {% else %}
      {% block linki2 %} {% endblock %}
    {% endif %}

    {% block linki3 %} {% endblock %}

  </body>
</html>

czat/templates/czat/index.html
<!-- templates/czat/index.html -->
{% extends "czat/baza.html" %}

{% block naglowek %}Witaj w aplikacji do zarządzania zasobami ludzkimi!{% endblock %}

{% block linki1 %}
  <p>Jesteś zalogowany jako {{ user.username }}.</p>
  {% if request.user.is_superuser %}
    <p><a href="{% url 'czat:rejestruj' %}">Zarejestruj użytkownika</a></p>
    <p><a href="{% url 'czat:users' %}">Użytkownicy</a></p>
    <p><a href="{% url 'czat:dodaj' %}">Dodaj wiadomość</a></p>
  {% else %}
    <p><a href="{% url 'czat:dodajn' %}">Zgłoś nieobecność</a></p>
  {% endif %}
  <p><a href="{% url 'czat:wiadomosci' %}">Wiadomości</a></p>
  <p><a href="{% url 'czat:nieobecnosci' %}">Nieobecności</a></p>
{% endblock %}
{% block linki2 %}
  <p><a href="{% url 'czat:loguj' %}">Zaloguj się</a></p>
{% endblock %}

czat/templates/czat/loguj.html
<!-- templates/czat/loguj.html -->
{% extends "czat/baza.html" %}

{% block naglowek %}Logowanie użytkownika{% endblock %}

{% block tresc %}
  {% if user.is_authenticated %}
    <p>Jesteś już zalogowany jako {{ user.username }}.</p>
  {% else %}
  <form method="POST">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Zaloguj</button>
  </form>
  {% endif %}
{% endblock %}

{% block linki3 %}
  <p><a href="{% url 'czat:index' %}">Strona główna</a></p>
{% endblock %}

czat/templates/czat/nieobecnosc_form.html
<!-- czat/wiadomosc_list.html -->
{% extends "czat/baza.html" %}

{% block naglowek %}Nieobecności{% endblock %}

{% block tresc %}
  <h2>Zgłoś nieobecność:</h2>
  <form method="POST">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Zapisz</button>
  </form>

  <h2>Lista nieobecności:</h2>
  <ol>
    {% for nieobecnosc in nieobecnosci %}
     <li>
        {% if nieobecnosc.autor.username == user.username %}
        <strong>{{ nieobecnosc.autor.username }}</strong> ({{ nieobecnosc.data_pub }}):
        <br /> {{ nieobecnosc.tekst }}
        <br /> {{ nieobecnosc.data_start }}
        <br /> {{ nieobecnosc.data_koniec }}
            &bull; <a href="{% url 'czat:edytujn' nieobecnosc.id %}">Edytuj</a>
            &bull; <a href="{% url 'czat:usunn' nieobecnosc.id %}">Usuń</a>
        {% endif %} 
    </li>
    {% endfor %}
  </ol>
{% endblock %}

{% block linki3 %}
  <p><a href="{% url 'czat:index' %}">Strona główna</a></p>
{% endblock %}

czat/templates/czat/nieobecnosc_list.html
<!-- czat/wiadomosc_list.html -->
{% extends "czat/baza.html" %}

{% block naglowek %}Nieobecności{% endblock %}

{% block tresc %}
  <h2>Lista nieobecności:</h2>
  <ol>
      {% if request.user.is_superuser %}
      {% for nieobecnosc in nieobecnosci %}
      <li>
          <strong>{{ nieobecnosc.autor.username }}</strong> ({{ nieobecnosc.data_pub }}):
          <br /> {{ nieobecnosc.tekst }}
          <br /> {{ nieobecnosc.data_start }}
          <br /> {{ nieobecnosc.data_koniec }} 
      </li>
      {% endfor %}
      {% else %}
      {% for nieobecnosc in nieobecnosci %}
      <li>
          {% if nieobecnosc.autor.username == user.username %}
          <strong>{{ nieobecnosc.autor.username }}</strong> ({{ nieobecnosc.data_pub }}):
          <br /> {{ nieobecnosc.tekst }}
          <br /> {{ nieobecnosc.data_start }}
          <br /> {{ nieobecnosc.data_koniec }}
              &bull; <a href="{% url 'czat:edytujn' nieobecnosc.id %}">Edytuj</a>
              &bull; <a href="{% url 'czat:usunn' nieobecnosc.id %}">Usuń</a>
          {% endif %} 
      </li>
      {% endfor %}
      {% endif %}
  </ol>

  {% if is_paginated %}
    <p>
    {% if page_obj.has_previous %}
      <a href="?page={{ page_obj.previous_page_number }}">Poprzednie</a>
    {% endif %}
      Strona {{ page_obj.number }} z {{ page_obj.paginator.num_pages }}.
    </span>
    {% if page_obj.has_next %}
      <a href="?page={{ page_obj.next_page_number }}">Następne</a>
    {% endif %}
    </p>
  {% endif %}
{% endblock %}

{% block linki3 %}
  <p><a href="{% url 'czat:index' %}">Strona główna</a></p>
{% endblock %}

czat/templates/czat/nieobecnosc_usun.html
<!-- czat/wiadomosc_list.html -->
{% extends "czat/baza.html" %}

{% block naglowek %}Nieobecności{% endblock %}

{% block tresc %}
  <h2>Usuń nieobecność</h2>
  <form method="POST">
    {% csrf_token %}
    <p>Czy na pewno chcesz usunąć nieobecność:<br /><i>{{ object }}</i>?</p>
    <button type="submit">Usuń</button>
  </form>
{% endblock %}

{% block linki3 %}
  <p><a href="{% url 'czat:index' %}">Strona główna</a></p>
{% endblock %}

czat/templates/czat/rejestruj.html
<!-- templates/czat/rejestruj.html -->
{% extends "czat/baza.html" %}

{% block naglowek %}Rejestracja użytkownika{% endblock %}

{% block tresc %}
    <form method="POST">
      {% csrf_token %}
      {{ form.as_p }}
      <button type="submit">Zarejestruj</button>
    </form>
{% endblock %}

{% block linki1 %}
  <p>Jesteś już zarejestrowany jako {{ user.username }}.</p>
{% endblock %}

{% block linki3 %}
  <p><a href="{% url 'czat:index' %}">Strona główna</a></p>
{% endblock %}

czat/templates/czat/user_form.html
<!-- czat/wiadomosc_list.html -->
{% extends "czat/baza.html" %}

{% block naglowek %}Użytkownicy{% endblock %}

{% block tresc %}
  <h2>Dodaj użytkownika:</h2>
  <form method="POST">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Zapisz</button>
  </form>

{% endblock %}

{% block linki3 %}
  <p><a href="{% url 'czat:index' %}">Strona główna</a></p>
{% endblock %}

czat/templates/czat/user_usun.html
<!-- czat/wiadomosc_list.html -->
{% extends "czat/baza.html" %}

{% block naglowek %}Wiadomości{% endblock %}

{% block tresc %}
  <h2>Usuń wiadomość</h2>
  <form method="POST">
    {% csrf_token %}
    <p>Czy na pewno chcesz usunąć wiadomość:<br /><i>{{ object }}</i>?</p>
    <button type="submit">Usuń</button>
  </form>
{% endblock %}

{% block linki3 %}
  <p><a href="{% url 'czat:index' %}">Strona główna</a></p>
{% endblock %}

czat/templates/czat/wiadomosc_form.html
<!-- czat/wiadomosc_list.html -->
{% extends "czat/baza.html" %}

{% block naglowek %}Wiadomości{% endblock %}

{% block tresc %}
  <h2>Dodaj wiadomość:</h2>
  <form method="POST">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Zapisz</button>
  </form>

  <h2>Lista wiadomości:</h2>
  <ol>
    {% for wiadomosc in wiadomosci %}
    <li>
      <strong>{{ wiadomosc.autor.username }}</strong> ({{ wiadomosc.data_pub }}):
      <br /> {{ wiadomosc.tekst }}
      {% if wiadomosc.autor.username == user.username %}
            &bull; <a href="{% url 'czat:edytuj' wiadomosc.id %}">Edytuj</a>
            &bull; <a href="{% url 'czat:usun' wiadomosc.id %}">Usuń</a>
      {% endif %}
    </li>
    {% endfor %}
  </ol>
{% endblock %}

{% block linki3 %}
  <p><a href="{% url 'czat:index' %}">Strona główna</a></p>
{% endblock %}

czat/templates/czat/wiadomosc_list.html
	

<!-- czat/wiadomosc_list.html -->
<html>
  <body>
    <h1>Wiadomości</h1>

    <h2>Lista wiadomości:</h2>
    <ol>
      {% for wiadomosc in wiadomosci %}
      <li>
        <strong>{{ wiadomosc.autor.username }}</strong> ({{ wiadomosc.data_pub }}):
        <br /> {{ wiadomosc.tekst }}
        {% if wiadomosc.autor.username == user.username %}
            &bull; <a href="{% url 'czat:edytuj' wiadomosc.id %}">Edytuj</a>
            &bull; <a href="{% url 'czat:usun' wiadomosc.id %}">Usuń</a>
        {% endif %}  
      </li>
      {% endfor %}
    </ol>

    {% if is_paginated %}
      <p>
      {% if page_obj.has_previous %}
        <a href="?page={{ page_obj.previous_page_number }}">Poprzednie</a>
      {% endif %}
        Strona {{ page_obj.number }} z {{ page_obj.paginator.num_pages }}.
      </span>
      {% if page_obj.has_next %}
        <a href="?page={{ page_obj.next_page_number }}">Następne</a>
      {% endif %}
      </p>
    {% endif %}

    <p><a href="{% url 'czat:index' %}">Strona główna</a></p>

  </body>
</html>

czat/templates/czat/wiadomosc_usun.html
<!-- templates/czat/wiadomosc_usun.html -->
<html>
  <body>
    <h1>Wiadomości</h1>

    <h2>Usuń wiadomość</h2>
    <form method="POST">
      {% csrf_token %}
      <p>Czy na pewno chcesz usunąć wiadomość:<br /><i>{{ object }}</i>?</p>
      <button type="submit">Usuń</button>
    </form>

    <p><a href="{% url 'czat:index' %}">Strona główna</a></p>
  </body>
</html>